[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  SKIP_ENV_VALIDATION = "true"

[context.production.environment]
  NEXT_PHASE = "phase-production-build"

[[plugins]]
  package = "@netlify/plugin-nextjs"